### ISSUE TITLE
关于侧边栏文字标题错乱问题

### ISSUE THREAD

**Issue by zhguo** [vuejs/vuepress#1009]
只有谷歌浏览器才会出现侧边栏标题文字不刷新，火狐、safari都显示正常。
我的导航栏有三个，点击切换导航栏的时候，对应的左边侧边栏的标题文字，只显示第一次显示的文字。
我的config.js文件代码如下：
```
sidebar: {
            '/page/guide/': getGuideSidebar('新手指南'),
            '/page/api/': getApiSidebar('在线API')

        }
```

```
function getGuideSidebar(title) {
    return [
        {
            title: title,
            collapsable: false,
            children: [
                '',
                'step',
                'apply',
                'protocol',
                'signature',
                'problem',
            ]
        }
    ]
}
```

**Comment by ulivz** [comment]
1. To report that only happens in the scene you are in, the best and direct way is to provide a reproduction repo (e.g. [vuepress-issue-example](https://github.com/ocavue/vuepress-issue-example)), otherwise I don't know where you are going wrong.
 
2. Please don't delete this template or we'll close your issue. (This sentence should be visible when you created the issue. 🙂)
