### ISSUE TITLE
怎么在组件中使用jquery？ 在组件中引入外部js无效！

### ISSUE THREAD

**Issue by Mrceel** [vuejs/vuepress#1017]
- [ ] I confirm that this is a issue rather than a question.

#### Other relevant information

- Your OS: 
- Node.js version: 
- Browser version: 
- Is this a global or local install? 
- Which package manager did you use for the install?

**Comment by Mrceel** [comment]
我想使用别人的插件和jquery插件， 我把他们放到了  .vuepress/public/js/ 里面 然后在cocomponents/home.vue 中引入他们   没有报错，也没有输出

**Comment by ulivz** [comment]
To ask a question about the issue you met, you should at least provide a reproduction repo, otherwise I don't know where you are going wrong, but I created a website that guides you on [how to use jQuery in VuePress](https://vuepress-examples.ulivz.com/jquery/).

---

Using issue to ask questions is not a good way, we recommend you to ask question in the [Discord server](https://vue-land.js.org/), [forum](https://forum.vuejs.org/), or [StackOverflow](https://stackoverflow.com/tags/vuepress)

**Comment by penggy** [comment]
@ulivz,  [how to use jQuery in VuePress](https://vuepress-examples.ulivz.com/jquery/) 这里提到使用 enhanceApp.js 引入 jquery, 我实测发现只有在 vuepress 1.x 版本下生效, 我想知道, 对于 vuepresss v0.x 应该如何引入 jquery. 我目前只知道 在 config.js 中添加 head, 但是之后在 vue 组件中直接使用 "$" 符, 提示 Error, 我想 vuepress v0.x 版本是不是有其它配置方法使得能够在 vue 组件中直接使用 jquery 的 "$" 符.
