### ISSUE TITLE
theme-default should support all pre-processor

### ISSUE THREAD

**Issue by mrleblanc101** [vuejs/vuepress#1114]
## Feature request
Hi,
I extended theme-default with custom components. 
Those components are SFC using scss as the pre-processor. 
The issue is that I can't access variables i created in palette.styl.
If i rename palette.styl in palette.scss, theme-default ignore the file.
Same goes for index.styl.
Shouldn't the theme load the correct file depending on the user configuration ?

#### What problem does this feature solve?
This would let the user use his prefered pre-processor. 
SASS/SCSS is far more popular than Stylus.

**Comment by janvennemann** [comment]
You can't mix and match stylus and scss (at least not in terms of variable access). And since the default theme uses stylus you need to use that when you extend the theme and have access to stylus defined variables.

You are free to use SASS/SCSS if you start from scratch with your own theme, though.

**Comment by ulivz** [comment]
See: https://vuepress.vuejs.org/guide/using-vue.html#using-pre-processors

**Comment by mrleblanc101** [comment]
As said, I was able to use SCSS in my vue component, but since the default theme use stylus, there is no way to access the default variables.

**Comment by mrleblanc101** [comment]
Is there a specific reason why you choose stylus instead of the more popular scss/sass ?
