### ISSUE TITLE
Bitbucket Edit Link goes to wrong link

### ISSUE THREAD

**Issue by nickngqs** [vuejs/vuepress#1235]
- [ x] I confirm that this is a issue rather than a question.

## Bug report
Editing links for Bitbucket doesn't work giving wrong URL to edit.

#### Version
0.14.8

#### Steps to reproduce
No steps required

#### What is expected?
It should go to the link below in order to work.
https://bitbucket.org/example-team/example-repo/src/master/docs/

#### What is actually happening?
Click on link goes to below url instead
https://bitbucket.org/example-team/example-repo/master/docs/

#### Other relevant information
Proposed feature as well to allow editing dynamic links in case individual api changes.

For example
It should go to the link below in order to work.

https://bitbucket.org/${organisation}/${repo-name}/${additional-url}

**Comment by ulivz** [comment]
Thanks for the report, since I don't use Bitbucket, could you help to fix it. Contribution welcome!

Ref: [related code](https://github.com/vuejs/vuepress/blob/master/packages/%40vuepress/theme-default/components/Page.vue#L140).

**Comment by SimonEast** [comment]
Thanks for the fix, but unfortunately there's no way to enable working `editLinks` for BitBucket *without also* enabling the repo link in the header (I'd like to use the former without the latter).

This is happening because the code is checking for the string `bitbucket.org` in the `repo` variable, not the `docsRepo` variable. Perhaps `if (bitbucket.test(repo))` should be `if (bitbucket.test(docsRepo))`?

**Comment by daltondiaz** [comment]
I don't why bitbucket put the **/src** in the end of repository, but when I did the edit link for bitbucket the configuration was:

```javascript
{
    ...
    repo: "https://bitbucket.org/myrepo/myproject/src",
    docsDir: "docs",
    docsBranch: "master",
    ...
}
```
So was only add the **/src** in the end of repo. I follow the pattern of github.

But ins't a problem these way and ins't necessary to change.
