### ISSUE TITLE
Easily configurable additional containers

### ISSUE THREAD

**Issue by owzim** [vuejs/vuepress#1260]
## Feature request

Currently, additional containers with custom names, args and output can only be added via this very verbose markdown-it configuration: https://github.com/markdown-it/markdown-it-container#example

In my opinion this is too much implementation detail and not abstract enough.

#### What problem does this feature solve?

Make it easier to implement additional custom containers

#### What does the proposed API look like?

```js
module.exports = {
  markdown: {
    containers: {
      foo(content, someArg = '') {
        return `<div class="foo ${someArg}">${content}</div>`;
      },
      bar(content, someArg1 = '', someArg2 = '') {
        return `<span class="bar ${someArg2}">${content}</span>`;
      }
    }
  }
}
```

#### How should this be implemented in your opinion?

Parse the `markdown.containers` object, and add the necessary `markdown-it` config internally, with parsers like in the given example and pass whateverer content and args are given to the `markdown.containers` functions.

#### Are you willing to work on this yourself?

I someone tells me where the right code spots are, sure.

**Comment by ulivz** [comment]
It's not very convincing to introduce a new top-level config(**especially not most of users need it**) at 1.x since you already have [Plugin API](https://vuepress.vuejs.org/plugin/) —— We hope the core to be as simple as possible and the Plugin API is for extension.

If you found that the Plugin API cannot resolve your problem, feel free to open a FR issue for that.

So please write a plugin to get it.
