### ISSUE TITLE
Sidebar group item cannot contain empty children

### ISSUE THREAD

**Issue by Armaldio** [vuejs/vuepress#1278]
- [x] I confirm that this is a issue rather than a question.

#### Version
vuepress: ^1.0.0-alpha.37

#### Steps to reproduce

yarn dev

#### What is expected?

The project should build and display the page.
Groups with empty childrens should only show the title as of vuepress@0.x

#### What is actually happening?

The build is successfull but the page is blank it an error is shown in the developer console \
![image](https://user-images.githubusercontent.com/3089715/52575425-2e126500-2dec-11e9-90bc-ef34aba42546.png)

#### Other relevant information

- Your OS: Windows 10
- Node.js version: v10.15.0
- Browser version: Chrome 72
- Is this a global or local install? > Locale
- Which package manager did you use for the install? > yarn

```js
sidebar: [
      {
        title: '1',
        children: [
          ['/intro/', 'Introduction'],
        ],
      },
      {
        title: '2',
        children: [],
      },
    }
}
```

**Comment by ulivz** [comment]
Thanks for the report, this is a regression bug of https://github.com/vuejs/vuepress/commit/11ce576b3e56f7fb7c701a8d58a2834d940e031a

Since a sidebar group item can also have a `path` item from [1.0-alpha.36](https://github.com/vuejs/vuepress/blob/master/CHANGELOG.md#100-alpha36-2019-02-03), so VuePress will intentionally convert the empty sidebar group item to a page item so that the headers of that page can be shown.
