### ISSUE TITLE
vuepress程序里面的网络请求在微信浏览器里无效

### ISSUE THREAD

**Issue by leach-chen** [vuejs/vuepress#1446]
- [ ] I confirm that this is an issue rather than a question.

#### Version
1.x-alpha
#### Steps to reproduce
在微信浏览器里执行我的网页，<a href="https://www.leachchen.com/"  target="_blank">https://www.leachchen.com/</a>，切换到对应版块如android或者游戏等页面时
里面有网络请求

#### What is expected?
数据可以正常出来
#### What is actually happening?
数据不能正常出来，在浏览器里数据可以正常出来，在微信浏览器里不行。我装了vconsole查看，只有一个SyntaxError: Unexpected token )/assets/js/app.8dc59315.js:7:64398 SyntaxError: Unexpected token )报错，其它的信息都看不到
#### Other relevant information

Other relevant information
Your OS: windows
Node.js version: v10.15.1
Browser version: chrome72
Is this a global or local install? local install
Which package manager did you use for the install?npm

**Comment by ulivz** [comment]
This error is caused by the incompatible syntax of temp files generated by VuePress:

![image](https://user-images.githubusercontent.com/23133919/54492946-e78dba00-4905-11e9-86c7-9c7473769489.png)

There is a consensus in the area of building tools that exclude `node_modules `in order to improve building performance, because temporary files of VuePress are generated by in `node_modules` by default, which leads to errors in those lower versions if we use advanced grammar (e.g. arrow functions here).

Before VuePress does anything, you can avoid this problem by modifying the location of temp folder via:

```bash
vuepress dev [docs] --temp .temp
vuepress build [docs] --temp .temp # do not forget to add .temp folder in .gitignore
```

Then the ES syntax can be transpiled correctly.

**Comment by leach-chen** [comment]
你说的是缓存的问题么，
vuepress dev [docs] --temp .temp
vuepress build [docs] --temp .temp # do not forget to add .temp folder in .gitignore

你说到的这两行是在什么地方处理？没大看懂，能否具体说明下，谢谢了

**Comment by leach-chen** [comment]
我之前用的是箭头函数，后面改了还是一样

**Comment by ulivz** [comment]
package.json

---

BTW, please use English so that all people can help you. 🙂

**Comment by leach-chen** [comment]
ok,follow your step,I add this code
 ```
 "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "docs:dev": "vuepress dev docs --temp .temp",
    "docs:build": "vuepress build docs --temp .temp"
  }
```
it also generate temp file,but when it browse in wechat,it still no data
