### ISSUE TITLE
Customer Containers is invalid

### ISSUE THREAD

**Issue by ChenFengHub** [vuejs/vuepress#1551]
#### Steps to reproduce
![image](https://user-images.githubusercontent.com/39979544/56350165-b8b47d80-61fc-11e9-92e7-aab6e7e28973.png)

**Comment by Shigma** [comment]
Are you using the default theme?

PS: DO NOT delete the issue templete, thanks.

**Comment by ChenFengHub** [comment]
The issue template is exists. I used version:1.0.0-alpha.44 is OK. When vuepress upgrade to version:1.0.0-alpha.47, the problem is  appear。Moreover, I use 「npm install -g vuepress@1.0.0-alpha.44」 to  download old version，the version still is v1.0.0-alpha.47。
![image](https://user-images.githubusercontent.com/39979544/56351350-7fc9d800-61ff-11e9-882c-a84fb43cbe69.png)

**Comment by Shigma** [comment]
1. You did delete some parts of the issue template.
2. In `1.0.0-alpha.47`, custom containers are only supported in `theme-dafault`. Try to use our default theme, or update your theme entry with:
https://github.com/vuejs/vuepress/blob/cafb991603152a2c0b758b9e14b4bb57f9988295/packages/%40vuepress/theme-default/index.js#L24-L41
3. You could not go back to `1.0.0-alpha.47` because VuePress does not use locked version.
4. 你的英语有点一言难尽（

**Comment by ChenFengHub** [comment]
问题解决了：现在tip应该是基于 vue-plugin-container，这个插件最近有更新，之前引入插件配置是‘@vuepress/container’，现在引入插件只要‘container’。谢谢！
![image](https://user-images.githubusercontent.com/39979544/56400913-f19a3400-6288-11e9-86e0-a787cc499dc3.png)
![image](https://user-images.githubusercontent.com/39979544/56400922-f8c14200-6288-11e9-9d54-fd47d2286c56.png)
