### ISSUE TITLE
vuepress build deletes old files

### ISSUE THREAD

**Issue by yunabe** [vuejs/vuepress#1577]
- [x] I confirm that this is an issue rather than a question.

#### Version

```
$ yarn vuepress --version
vuepress/1.0.0-alpha.47 darwin-x64 node-v10.15.3
```

#### Steps to reproduce

1. Build a vuepress site: `vuepress build`
2. Publish the site
3. Open a page on your browser. Keep the page opened until prefetched caches on browsers are invalidated.
4. Update the content of another page.
5. Build a vuepress site again and publish it. This deletes the old version of the updated page.
6. In the browser tab you opened in Step 3, click a link to the page you updated at Step 4.

I created a minimal example repository:
1. `git clone https://github.com/yunabe/vuepressbug1577`
2. `cd vuepressbug1577`
3. `yarn`
4. `yarn build`
5. `yarn server &`
6. Open http://localhost:8888/. Keep the tab opening.
7. `echo "additional content" >> page_a.md`
8. `yarn build`
9. In the browser tab opened at Step (6), click "Page A". This fails.
    https://www.youtube.com/watch?v=9-NorHbuDjc

I checked [Deploying doc](https://v1.vuepress.vuejs.org/guide/deploy.html). But I have no idea how we can update vuepress sites without breaking old pages on users browser.

#### What is expected?

- Old files are not cleared by `vuepress biuld`.
- Or, `vuepress` detects the update of contents and reload pages

#### What is actually happening?

- Old files are deleted from `.vuepress/dist` directory.
- On page navigations, vuepress fails to load page contents (404 response) internally.
   But it looks vuepress does not detect it.

#### Other relevant information

- Your OS: `Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64`
- Node.js version: `v10.15.3`
- Browser version: `Google Chrome 73.0.3683.103 (Official Build) （64 bits）`
- Is this a global or local install? : `local`
- Which package manager did you use for the install?: `yarn`
- Does this issue occur when all plugins are disabled?: `Yes`

**Comment by ulivz** [comment]
Thanks for your interest in VuePress, but why not deleting the old files?

**Comment by yunabe** [comment]
> but why not deleting the old files?

Because it breaks the page navigation of old vuepress pages living on users browser.
Let me repeat my previous comment in case you missed:

**What is actually happening?**

- On page navigations, vuepress fails to load page contents (404 response) internally. But it looks vuepress does not detect it.

**Comment by Livven** [comment]
This has been annoying to us as well. If a VuePress site is updated (i.e. rebuilt) while someone has a page open, any further client-side navigation will stop working due to the old `.js` files becoming unavailable. Instead the user will only see the progress bar getting stuck, as shown in the video.

I think the second solution is better. You can't really keep the old files if you build in a clean environment. Whenever VuePress gets a 404 response when trying to load `.js` files ([example](https://stackoverflow.com/questions/538745/how-to-tell-if-a-script-tag-failed-to-load/4163527#4163527)), it should disable the client-side navigation and simply redirect the user to the new URL.
