### ISSUE TITLE
markdown extendMarkdown-config aren't working 

### ISSUE THREAD

**Issue by ZengTianShengZ** [vuejs/vuepress#1586]
markdown extendMarkdown-config aren't working 

Version
    "vuepress": "^1.0.0-alpha.47"

Steps to reproduce
open config.js in .vuepress
add the following block to your config

```
markdown: {
    extendMarkdown: md => {
      md.use(require('markdown-it-container'), 'spoiler', {
        render(tokens, idx) {
          var m = tokens[idx].info.trim().match(/^spoiler\s+(.*)$/);
          if (tokens[idx].nesting === 1) {
            // opening tag
            return '<details><summary>' + m[1] + '</summary>\n';   
          } else {
            // closing tag
            return '</details>\n';
          }
        }
      });
    }
  },
```
I expect  

```
::: spoiler 
click me 
*content*
:::
```
 Output:

```
 <details><summary>click me</summary>
 <p><em>content</em></p>
 </details>
```

but aren't working 

Other relevant information
Your OS: Mac os 10.14.4 (18E226)
Node.js version: v11.12.0
Browser version: Chrome 70.0.3538.77
Is this a global or local install? local
Which package manager did you use for the install? yarn

**Comment by ulivz** [comment]
Thanks for your interest in VuePress.

But I cannot reproduce this issue and I can confirm that this isn't an issue. 

I think you should not restart dev server, any changes that modify markdown need you to restart server manually at present, otherwise the compiled result of markdown will be the cache.

BTW, you can simply use the [vuepress-plugin-container](https://github.com/vuepress/vuepress-plugin-container) to get it:

```js
module.exports = {
  plugins: [
    [
      "container",
      {
        type: "vuepress",
        before: '<pre class="vue-container"><code>',
        after: "</code></pre>"
      }
    ]
  ],
}
```
