### ISSUE TITLE
FR: Expose all default loaders.options to config

### ISSUE THREAD

**Issue by matsp** [vuejs/vuepress#169]
It would be nice to configure all default loaders e.g. sass-loader with vuepress config file. I would prefer the way that is implemented for the postcss-loader. It's easier than configure webpack through vuepress config file.

**Comment by ulivz** [comment]
`sass`、`scss`、`stylus` and `less` have been configured internally and use `postcss-loader` by default so that if you want to use them at your project, you only need to install the corresponding dependencies.

For pre-processors that do not have built-in webpack config support, you will need to [extend the internal webpack config](https://vuepress.vuejs.org/config/#configurewebpack)

**Comment by matsp** [comment]
That's okay. But I need to adapt the sass-loader e.g. the includePaths  .

**Comment by ulivz** [comment]
Cool, I thought about this before. someone may need this feature.

**Comment by ulivz** [comment]
Fixed at #178

**Comment by matsp** [comment]
Thanks!

**Comment by matsp** [comment]
Setting the following has no effect for me:

```javascript
scss: {
  includePaths: [nodeModules]
}
```

@ulivz I transfered this from my own webpack config. nodeModules will be absolute resolved. Anything Iam not thinking off=
