### ISSUE TITLE
Section links should not be covered by navbar

### ISSUE THREAD

**Issue by johnpapa** [vuejs/vuepress#1768]
When clicking on a section link inside of a page, the page scrolls to show that section at the top. However, the navbar covers the header. It would be great to adjust this so the header is not hidden
![2019-08-09_14-44-09 (1)](https://user-images.githubusercontent.com/1202528/62801722-5ab1eb80-bab4-11e9-9d6f-aec0893f07b8.gif)

**Comment by kefranabg** [comment]
Thanks for opening the issue, we'll investigate soon 👍 

**Reproduction link:** [https://github.com/johnpapa/vscode-peacock/tree/master/docs](https://github.com/johnpapa/vscode-peacock/tree/master/docs)

**Comment by CodesOfRa** [comment]
Hi @kefranabg and @johnpapa 

I don't think this issue is from vuepress default theme . 
I  did a quick test in codesandbox and it works as expeted. Check this link : https://w6nz0vxw8.sse.codesandbox.io/guide/#theme-customization

The h2 and h3 styles from default theme are overridden here  lines `31,32`: https://github.com/johnpapa/vscode-peacock/blob/master/docs/.vuepress/styles/palette.styl#L31 .

(I tested removing them and the issue is fixed )

**Comment by kefranabg** [comment]
@johnpapa Do you confirm so we can process the issue ?

**Comment by johnpapa** [comment]
yes, i confirmed this, thanks. it is due to the styling on the headers that I have.
