### ISSUE TITLE
Usage Guidance

### ISSUE THREAD

**Issue by brsanthu** [vuejs/vuepress#179]
I have a general question about where we could use vuepress. 

Main page says, it is minimalistic documentation generator. Is it just that or can be used for other type of site building, like below?

1. Product Documentation site (sure, main page says it is minimalist documentation generator)
2. Api documentation (like swagger or other spec converted for consuming)?
3. Company dotcom sites (here there is lots of content and media, and may have to use components)
4. Integrate payment systems (like stipe) into the page?
5. Support for different page templates (for ex., one part of site wants to use different theme/page structure than others)?

**Comment by ulivz** [comment]
Thanks!

Since you can [use Vue](https://vuepress.vuejs.org/guide/using-vue.html) and [use custom theme](https://vuepress.vuejs.org/guide/custom-themes.html) at VuePress, so you can do anything that Vue can do, as long as you want to do.

The built-in default theme will be only focused on documentation sites. blog support will be done in a separate theme.

Other stuffs, it's up to you.
