### ISSUE TITLE
About Custom Layout for Specific Pages

### ISSUE THREAD

**Issue by superbiger** [vuejs/vuepress#1820]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
https://vuepress.vuejs.org/zh/default-theme-config/#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%A1%B5%E9%9D%A2%E7%B1%BB

When I use special layout, not keeping navbar
#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by kefranabg** [comment]
Hi @superbiger,

This is an expected behaviour, layout includes everything including navbar. What your looking for might be [theme inheritance](https://v1.vuepress.vuejs.org/theme/inheritance.html#motivation) or [ejecting default theme](https://v1.vuepress.vuejs.org/theme/default-theme-config.html#ejecting). Feel free to reopen this issue if this was not clear.
