### ISSUE TITLE
[Question] Inconsistent module definition

### ISSUE THREAD

**Issue by CITguy** [vuejs/vuepress#200]
Documentation has the [Config File](https://vuepress.vuejs.org/guide/basic-config.html#config-file) defined as a CommonJS module (`module.exports`), but the [App Level Enhancements](https://vuepress.vuejs.org/guide/basic-config.html#app-level-enhancements) section on the same pages is documented as an ES module (`export default`). 

Is this intentional?
Are there any plans to standardize?

**Comment by ulivz** [comment]
Thanks, If you know more about the working mechanism of VuePress you will find that it is intentional.

App level(es module) is for client side which will be transpiled by buble, while the config file will be loaded by node.js so it's cjs.

No plan to standardize(bundle node level's script) at present.
