### ISSUE TITLE
没有更新成功

### ISSUE THREAD

**Issue by TimSpan** [vuejs/vuepress#2000]
为什么我的vuepress博客，本地运行正常，但是更新成功后，我的博客文章还是404，这是为啥？本地运行没问题。更新也没问题。git仓库也没问题，但是访问就404，总之就是没有更新上去，但是git仓库是存在的。我的博客地址https://timspan.github.io/documents/

**Comment by ludanxer** [comment]
Hi @TimSpan ,

Pls describe your problem in English next time, so everyone can help you.

The link you provided is working fine, so I do not quite understand what your problem is.

Can you push your corresponding code to that repo's `master` branch? So people can see your configuration. And can you provide more detail about your problem? How to reproduce it?

Relevant document:  [Deploy on GitHub-Pages](https://vuepress.vuejs.org/guide/deploy.html#github-pages)

---

Simplified Translation:

Why is my Vuepress blog getting `404` after update? It works well in my local environment. The address for my blog is: [https://timspan.github.io/documents/](https://timspan.github.io/documents/)

**Comment by kefranabg** [comment]
Thanks for the translation @ludanxer.

@TimSpan could you provide a link to a minimal reproduction repository?

**Comment by Mister-Hope** [comment]
Since you are using chinese, I will reply you in chinese.

我觉得不是vuepress的问题，你在文件中使用了中文，如果你花上一小点事件了解一下node，你就会发现node不支持中文路径，所以你那些导航栏链接显然生成不出来，路径都是`/.html`结尾的(不要天真的以为vuepress能够帮你渲染出`/php/php基础.html`的地址)

另外你来这开了一个issue，然后连一个源码都没有？难道其他人还得照着你打包出来的东西去逆向猜你源码么？别逗了!

---

Node doesn't support path containing chinese, so you can not use file name like `php基础.md`.

@kefranabg  Suggest closing this issue

**Comment by TimSpan** [comment]
> Since you are using chinese, I will reply you in chinese.
> 
> 我觉得不是vuepress的问题，你在文件中使用了中文，如果你花上一小点时间了解一下node，你就会发现node不支持中文路径，所以你那些导航栏链接显然生成不出来，路径都是`/.html`结尾的(不要天真的以为vuepress能够帮你渲染出`/php/php基础.html`的地址)
> 
> 这个issue虽然很简单，但是这ok，我们也愿意帮你解答一下，不过如果你的基础的确很差的话，友情建议你下次去论坛提问，而不是来这里开一个issue。 但是，你这个开issue找不到问题没法给大家提供有用的信息不说，源码都不给，这事就挺让人不舒服的了。难道其他人还得照着你打包出来的东西去逆向猜你源码么？别逗了!
> 
> Node doesn't support path containing chinese, so you can not use file name like `php基础.md`.
> 
> @kefranabg Suggest closing this issue

我错了。

**Comment by TimSpan** [comment]
> 嗨@TimSpan，
> 
> 请下次用英语描述您的问题，以便每个人都能为您提供帮助。
> 
> 您提供的链接工作正常，因此我不太了解您的问题所在。
> 
> 您可以将相应的代码推送到该仓库的`master`分支吗？这样人们就可以看到您的配置。您能否提供有关您的问题的更多详细信息？如何复制它？
> 
> 相关文档： [在GitHub-Pages上部署](https://vuepress.vuejs.org/guide/deploy.html#github-pages)
> 
> 简体翻译：
> 
> 为什么我的Vuepress博客`404`在更新后会收到？在我的本地环境中效果很好。我的博客地址是：[https](https://timspan.github.io/documents/) : [//timspan.github.io/documents/](https://timspan.github.io/documents/)

**Comment by TimSpan** [comment]
Sorry to bother you. My problem has been solved. @ludanxer @kefranabg @Mister-Hope

**Comment by TimSpan** [comment]
Thank you for your

**Comment by sodatea** [comment]
Node 是支持中文路径的……
如果出现问题的话，可以认为是 bug （参考之前的类似 issue：#473 #628 #1604 #1732）
不过这个 issue 确实有效信息太少了，无法判断。
