### ISSUE TITLE
When the page scrolls about one screen high, it will automatically jump to the top

### ISSUE THREAD

**Issue by xuekai-china** [vuejs/vuepress#2037]
- [ ] I confirm that this is an issue rather than a question.

#### My project address: http://www.xwbuilders.com:9018/soonspacejs/Docs/api/

- Output of `npx vuepress info` in my VuePress project:

**Comment by ludanxer** [comment]
Hi @xuekai-china ,

There is indeed unexpected behavior on the page you provide. But I'm not sure it's VuePress' problem.

Can you pls make your repo public so we can locate the problem? Or build a minimal reproduction?

**Comment by xuekai-china** [comment]
@ludanxer 

My, please wait a moment, I will open the code of the document part to my GitHub account.

**Comment by xuekai-china** [comment]
@ludanxer 
Hello, the warehouse has been built, and your account has joined the partnership. https://github.com/xuekai-china/soonspacejs-docs

**Comment by ludanxer** [comment]
Well, it seems that you [eject the official theme](https://vuepress.vuejs.org/theme/default-theme-config.html#ejecting)  and customized it. Ejecting does give you lots of freedom but as the document warns:

> Once you eject, you are on your own and won’t be receiving future updates or bugfixes to the default theme even if you upgrade VuePress.

Don't have time to dig deep into your project. But I think the bug may be caused by your customization or it may be a VuePress' bug, I'm not sure. My suggestion is: try to use [Theme Configuration](https://vuepress.vuejs.org/guide/basic-config.html#theme-configuration) and [Theme Inheritance](https://vuepress.vuejs.org/theme/inheritance.html#theme-inheritance) to customize the official theme instead of ejecting it.

As a workaround, disable the `@vuepress/active-header-links` plugin seems to "fix" it:
```
['@vuepress/active-header-links', false]
```

**Comment by xuekai-china** [comment]
Okay, thank you！
