### ISSUE TITLE
markdown.extractHeaders config option does not work

### ISSUE THREAD

**Issue by Otto-J** [vuejs/vuepress#2071]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

** English is not very good **

try change option `config.js` to be: `markdown.extractHeaders:["h1", "h2", "h3"]`, on Post page, try to get `this.$page.headers` still return h2 and h3

and I changed the file: `node_modules/@vuepress/core/lib/node/Page.js` line117:

```js
const headers = extractHeaders(
          this._strippedContent,
          ['h1','h2', 'h3'], // add 'h1' to here.
          markdown
        )
```

it worked.

so, I think `markdown.extractHeaders` option does not work.

#### What is expected?

on post page, get `this.$page.headers` includes `h1` level

#### Other relevant information

```
"vuepress": "^1.2.0"

```

in Chinese:

制作主题时候，想通过设置`makdown.extractHeaders`, 来 `this.$page.headers` 获取到所有的heading 标签，感觉是硬解码写成固定的了，配置的选项也不生效。

**Comment by ludanxer** [comment]
Hi @Otto-J 

Thanks for the report, `markdown.extractHeaders` option is currently not available in the `1.2.0` release.

This feature is implement by #1945 ,which is after the release of `1.2.0`, please patiently wait for the next release. Thanks.

This issue is also related to #1931 , the document is updated faster than the release.

**Comment by Otto-J** [comment]
@ludanxer Thanks.

**Comment by bretterer** [comment]
Thank you for this work as I tried to implement this in #1111 ... Is there any idea when the next release will happen which will include this work?

**Comment by quannetwork** [comment]
Love this feature <3. I'm still looking forward to it
