### ISSUE TITLE
Chinese title in sidebar is not properly highlighted after refresh

### ISSUE THREAD

**Issue by huiminxu** [vuejs/vuepress#2078]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

Bug：When the address bar refreshes the page, the left side is no longer selected

#### What is expected?
Expected： When the address bar refreshes the page, the left side is selected
#### What is actually happening?
![image](https://user-images.githubusercontent.com/33274229/70692268-ed2dfa00-1cf5-11ea-9793-ec393d3b3a44.png)
![image](https://user-images.githubusercontent.com/33274229/70692274-f1f2ae00-1cf5-11ea-9412-259c13356a9f.png)

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by huiminxu** [comment]
![image](https://user-images.githubusercontent.com/33274229/70691826-fe2a3b80-1cf4-11ea-80e6-f1a89d5cf945.png)
![image](https://user-images.githubusercontent.com/33274229/70691830-02eeef80-1cf5-11ea-89e3-de56827c5969.png)

When the address bar refreshes the page, the left side is no longer selected

**Comment by ludanxer** [comment]
Hi @huiminxu ,

Can you provide more detail about how to reproduce this problem? or a minimal reproduction?

**Comment by huiminxu** [comment]
When developing a page, the menu bar on the left shows the secondary title, click on a title, the right side of the display the contents of the title, the selected color on the left and the address bar is # 2 titles 。but refreshed in the address bar , the right still can display the contents of the corresponding title, but not on the left side of the selected state

**Comment by ludanxer** [comment]
Thanks a lot, this is also happening on the official website. 

I think this problem is happening whenever the **URL contains Chinese characters**. Try [this Chinese translation](https://vuepress.vuejs.org/zh/config/#%E5%9F%BA%E6%9C%AC%E9%85%8D%E7%BD%AE), when you open the page, the title in the sidebar is not highlighted with green. When you click on the `基本配置` in the sidebar, it's highlighted but after refreshing the page, the highlight is gone again.

And the [English site](https://vuepress.vuejs.org/config/#basic-config) is giving the expected behavior.

@huiminxu  Can you rename the issue's title to something like `Chinese title in sidebar is not properly highlighted after refresh`
