### ISSUE TITLE
Are environment variables supported?

### ISSUE THREAD

**Issue by morrislaptop** [vuejs/vuepress#214]

**Comment by yyx990803** [comment]
Please be more specific with the question. You can use webpack config APIs to add your own environment variables with DefinePlugin.

**Comment by 0biWanKenobi** [comment]
Since this issue is one of the first results from a Google "vuepress environment variables" search, I'll share how to do it if using Vite as a bundler:

1. create a `.env.development` file and a `.env.production` one
2. define your vars, like  `VITE_APP_VARIABLENAME` (remember they _have to_ start w/ `VITE_APP`)
3. in your vuepress.config.ts (or .js) do this:

```
import { loadEnv } from 'vite';

const mode = process.env.NODE_ENV || 'development';
process.env = { ...process.env, ...loadEnv(mode, process.cwd()) };

const YourVariable = process.env.VITE_APP_VARIABLENAME;
```

The above code leverages `vite` and its `loadEnv` function to load the environment variables you defined in your `.env` file. It also leverages the fact that when running the `vuepress` CLI command we have `process.env.NODE_ENV` set to development or production based on whether we ran `vuepress dev` or `vuepress build`. This way we can load different `.env` files!

**Comment by andrey-helldar** [comment]
VuePress 2.0.0-beta.35

Work for me:

```bash
npm i dotenv -D
```

```javascript
// config.js

require('dotenv').config();

module.exports = {
    // ...

    plugins: [
        [
            '@vuepress/docsearch',
            {
                appId: process.env.VITE_APP_ALGOLIA_APP_ID,
                apiKey: process.env.VITE_APP_ALGOLIA_API_KEY,
                indexName: process.env.VITE_APP_ALGOLIA_INDEX_NAME
            }
        ]
    ]
}
```

**Comment by earlman** [comment]
@andrey-helldar Seems to have stopped working on VuePress 2.0.0-beta.41 😕 Any ideas?

**Comment by andrey-helldar** [comment]
@earlman, I'm still using VuePress `2.0.0-beta.35` version. Sorry.
