### ISSUE TITLE
build之后，public中的文件移动到根目录下，但生成的html中路径没有改动

### ISSUE THREAD

**Issue by Roy-Kid** [vuejs/vuepress#2202]
- [x] I confirm that this is an issue rather than a question.

## Bug report
我将所有的照片当到了.vuepress/public 下面，所有引用都写成/logo.png的形式，然后vuepress dev，一切正常。但是build之后，html中主logo和左上角brand路径都是正常的，变成了xx/logo.gif，但是md中的路径仍然是/logo.gif。请赐教，不太清楚中间发生了什么。
#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

**Comment by ludanxer** [comment]
Hi, could you please use English so everyone could understand and help you? Thanks!

And I'm not very sure what your problem is, but I think [baseURL](https://vuepress.vuejs.org/guide/assets.html#base-url) in the document would help?

If not, could you please provide `Steps to reproduce` as the issue template suggests? Thanks.

**Comment by Roy-Kid** [comment]
sorry about that. I have removed all the globe modules include vuepress and then, use yarn add them locally, and it worked. i think this is due to the conflict of npm and yarn maybe. Sorry for bothering you again, i am the freash man of js...
