### ISSUE TITLE
添加初始化工作空间功能

### ISSUE THREAD

**Issue by liuweiGL** [vuejs/vuepress#2311]
#### What problem does this feature solve?
每次都用手动创建 docs 目录以及 vuepress 配置文件。

#### What does the proposed API look like?
vuepress init

#### How should this be implemented in your opinion?
自动创建 docs 目录、 .vuepress 目录以及默认的 config.js 信息。

#### Are you willing to work on this yourself?
暂时不会。

**Comment by Mister-Hope** [comment]
It's a nice idea. I just create a branch and try to work on this feature. Then I found this api really did little work for you:

1. create a folder you pass to the cli (e.g.: `vuepress init src` will create src folder)
2. create an empty `.vuepress` folder in it
3. create a `config.js` with: ( I am not sure because vuepress can work with no config file)

```js
module.exports = {
};
```

It is this really a complicated work? I think not. 😅 So why do we need this api? I thought for a while, and maybe you want the cli to ask you about title, description and so on for you to type it. Is that what you want?

**Comment by ludanxer** [comment]
Hi @liuweiGL , please use English next time so everyone could understand and help you, Thanks!

Currently, I think there is an official scaffolding tool [create-vuepress](https://github.com/vuepressjs/create-vuepress) see #1415
