### ISSUE TITLE
Add create CLI command

### ISSUE THREAD

**Issue by bencodezen** [vuejs/vuepress#2438]
## Feature request

Users should be able to generate a VuePress project with the basic features using a `vuepress create $directoryName` command.

#### What problem does this feature solve?

- Improves onboarding experience

#### What does the proposed API look like?

1. `vuepress create ${directoryName}`

#### How should this be implemented in your opinion?

Using the existing infrastructure built on CAC.

#### Are you willing to work on this yourself?

Yes

**Comment by ulivz** [comment]
Do you mean scaffolding bin? I don't think that it should be addressed under the VuePress core, since `vuepress` is an build-time dependency under a project, while a scaffolding tool is usually a global dependency.

[create-vuepress](https://github.com/vuepressjs/create-vuepress) should be responsible for that.

**Comment by bencodezen** [comment]
@ulivz Sounds great. Would it be possible to get updated permissions on the vuepressjs organization? I'd love to get in there to update some of the packages if possib.e

**Comment by bencodezen** [comment]
@ulivz Please correct me if I'm wrong, but it seems that the create-vuepress repo you created only works with yarn. Is there a way for users to use this using

**Comment by bencodezen** [comment]
@ulivz I figured it out. Turns out the `yarn create` equivalent is `npx create-`. Docs are updated accordingly!
