### ISSUE TITLE
Features markdown not working

### ISSUE THREAD

**Issue by luisDanielRoviraContreras** [vuejs/vuepress#251]
When I try to put in bold the titles inside **features** I get this error there is some way to do it or does not have support for markdown.

<img src="https://i.imgur.com/WUx6Xte.png">

> Uncaught (in promise) Error: Module build failed: YAMLException: unidentified alias "*Experience**" at     
   line 5, column 24:
   title: \*\*Experience*\* design

**Comment by yyx990803** [comment]
FYI this is not something we are going to support. Markdown handling in frontmatter increases the complexity quite a bit. If you want to customize the homepage, you can implement it yourself with plain HTML in the content section.

**Comment by mattcotter** [comment]
I found a pretty simple solution that doesn't require any additional workarounds and uses packages already built in Vuepress. Since this was the first thing that popped up in google, I'll go ahead and document my solution here.

You can route your YAML through a simple custom component like this:

**Component.vue**
```
<template>
    <div>
        <span v-html="md.render($page.frontmatter.description)"></span>
    </div>
</template>

<script>
 var md = require('markdown-it')();
 export default {
        data() {
            return {
                md: md
            }
        }
    }
</script>
```

**Your markdown file will look something like this:**
```
---
description: Lorem Ipsum Dolor Amit
---

<Component></Component>
```

You should also be able to use your component inside your `Layout.vue` file as well if you want but for my purposes I needed the added flexibility of being able to place the component anywhere I wanted in my content.

This solution utilizes the `markdown-it` package that Vuepress uses so you just need to invoke it in your component. As this will render the HTML in plaintext, you will need to parse it through the `v-html` directive to output in the desired format.

Hope this helps someone. If there's a better solution or any holes, feel free to add on to it.

* [`v-html` directive](https://vuejs.org/v2/api/#v-html)
* [`markdown-it` render function](https://markdown-it.github.io/markdown-it/#MarkdownIt.render)
