### ISSUE TITLE
When we quick start, The directory structure of it isn't recommended form

### ISSUE THREAD

**Issue by twtwtw-gj** [vuejs/vuepress#2613]
- [ ] I confirm that this is an issue rather than a question.

#### Steps to reproduce
Following https://vuepress.vuejs.org/guide/getting-started.html#quick-start, I commanded 
```bash
yarn create vuepress-site [optionalDirectoryName]
```

#### What is expected?
The file "package.json" is in root directory.
#### What is actually happening?
"package.json" is in "docs" directory.
#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

We should change the latters of the guide.

**Comment by adamb** [comment]
I had the same issue.  I can't seem to get vuepress to work.  I tried going down the npm path first since I didn't have yarn installed.  After following the NPM instructions I ran `npm run dev` and got the localhost running but nothing rendering.  There were errors in the javascript console.   Looking back at the `npm i -D vuepress` there were a bunch of warnings saying `You must install peer dependencies yourself.`

Ok, there is a warning at the top of the page about webpack.  (This is a new project, so how do I know if I'm using webpack?) Anyway, maybe I am using webpack.  Let's try yarn.

Install yarn and try the `yarn create vuepress-site` and I get the same reported by  @twtwtw-gj  here.  No packages.json, etc. 

I really would like to use Vuepress and a correct  **Get Started** page would really help!  

I would also suggest adding commands on how to run things once they are installed.  Under **Quick Start** there should be instructions on how to run the newly installed thing.   I'm guessing `yarn doc:dev` but that doesn't work since there is no package.json for starters.
