### ISSUE TITLE
Shouldn't $site.title become the HTML title tag? 

### ISSUE THREAD

**Issue by tomcam** [vuejs/vuepress#263]
$site.description becomes the descript meta tag. Shouldn't $site.title become an HTML title tag? I'll do the PR if you think it's a good idea.

**Comment by ulivz** [comment]
Thanks, but it's unnecessary, and what you said is not correct completely.  there are some data you can directly use at default theme or custom theme:

- `$siteTitle`: presentational title, would be `$localeConfig.title`, fallback to `$site.title`.
- `$title`: used for `<title>` tag, it would be `siteTitle` + `|` + `pageTitle`.
- `$description`: used for description meta tag.

More detail, please refer to `lib/app/dataMixin.js`. 

since now our core API is not completely stable, so we will document for them later.
