### ISSUE TITLE
dead link in documentation

### ISSUE THREAD

**Issue by JOduMonT** [vuejs/vuepress#2795]
https://vuepressbook.com/default-theme/hero-text.html
![image](https://user-images.githubusercontent.com/5204724/107595660-ee372000-6c47-11eb-9db2-3110af1ff044.png)
== [404](https://github.com/vuejs/vuepress/blob/master/lib/default-theme/Home.vue)

**Comment by d-pollard** [comment]
Good catch! Would you want to submit a PR fixing this?

**Comment by thecoden** [comment]
This issue is not actually with this repository. The documentation this issue occurs on is in this repository:
https://github.com/tomcam/vuepress.github.io/issues

I found this when I could not find the file to edit in this repo, and ultimately found it via the "Feedback" link on the vuepressbook.com website.

@JOduMonT, could you submit this issue there or take a moment to send a pull request?

**Comment by d-pollard** [comment]
@thecoden - good eye, going to close this as it is unrelated to this repo
