### ISSUE TITLE
Global Footer in Default Theme

### ISSUE THREAD

**Issue by raytu** [vuejs/vuepress#339]
It seems that footers are defined separately in each README.md front matter. Is there a way to define a global footer for all pages from a single file or themeConfig?

**Comment by meteorlxy** [comment]
Not yet in default theme. 

In fact, in current default theme, only the `home` layout has footer. There is a `<slot name="page-bottom" slot="bottom"/>` for `page` layout to push something like a footer (current some ads for vuejs official theme, lol)

**Comment by ghys** [comment]
I have the same requirement, I tried creating a new `vuepress/theme/Layout.vue` reusing the layout component from the default theme as shown above.

The problem is, my `override.styl` is not taken into account anymore (I override `$accentColor` etc.), presumably because of this:
https://github.com/vuejs/vuepress/blob/d9b290b39863c51f60468b7091d82f52a6c7335a/lib/prepare.js#L64
(useDefaultTheme is now false)

Would it make sense to always allow override.styl, to allow custom themes based on the default theme to still override stylus variables?

**Comment by ulivz** [comment]
As @meteorlxy said, it shouldn't be included in default theme.

@ghys You should open another issue for feature request of `override.styl` in custom theme.

**Comment by iamchathu** [comment]
The solution is not works with current version.

**Comment by imaegoo** [comment]
> 
> 
> The solution is not works with current version.

### New solution for vuepress v1.5.4

Create 2 files

1. `.vuepress/theme/index.js`
```
module.exports = {
  extend: '@vuepress/theme-default'
}
```
2. `.vuepress/theme/layouts/Layout.vue`
```
<template>
  <ParentLayout>
    <template #page-bottom>
      <div>My custom footer</div>
    </template>
  </ParentLayout>
</template>

<script>
import ParentLayout from '@parent-theme/layouts/Layout.vue'

export default {
  name: 'Layout',

  components: {
    ParentLayout
  }
}
</script>
```

**Comment by BroJenuel** [comment]
Changing the footer ignores some of my plugin like the vuepress-theme-succinct.
