### ISSUE TITLE
Using Vue in Markdown

### ISSUE THREAD

**Issue by wh-Coder** [vuejs/vuepress#455]
- node v8.4.0
- vuepress v0.8.4

I used pug preprocessing in hello.md according to [documentation](https://vuepress.vuejs.org/zh/guide/using-vue.html#%E4%BD%BF%E7%94%A8%E9%A2%84%E5%A4%84%E7%90%86%E5%99%A8), but it was invalid. Is there a problem with my configuration? 

hello.md
```
<style lang="stylus" scoped>
.hello
    color red
</style>

<template lang="pug">
.hello {{ msg }}
</template>

<script>
export default {
    data() {
        return {
            msg: 'hello'
        }

    },
}
</script>
```

**Comment by meteorlxy** [comment]
p.hello ?

**Comment by wh-Coder** [comment]
@meteorlxy 

There is no error, the page can not be resolved

![image](https://user-images.githubusercontent.com/26110097/40094390-5145a08c-58f9-11e8-9c51-df9b0a44d396.png)

**Comment by ulivz** [comment]
Could you provide your reproduction repo?

**Comment by wh-Coder** [comment]
@ulivz 

In addition to downloading dependencies, what else do you need to configure?

thx

https://github.com/wh-Coder/vuepress-pug

**Comment by ulivz** [comment]
Thanks for your reporting, for now, you cannot use `<template>` in markdown file, since VuePress will use `<template>` to wrap the whole markdown's content, so your `<template>` tag will be finally handled by `Vue` instead of `vue-loader` (i.e. it's ignored.).

- Why do we don't support it？

Refer to specification of [SFC](https://vue-loader.vuejs.org/spec.html#template):

> Each *.vue file can contain at most one <script> block at a time.

A file corresponds to a component, so we shouldn't support it, otherwise it will cause all your markdown content must be written in `<template>`.

It is recommended that for scenarios that require the use of the template preprocessor, please separate your code as a single file component at `.vuepress/components`.

**Comment by ulivz** [comment]
cc @yyx990803

**Comment by wh-Coder** [comment]
@ulivz 

thank you very much
