### ISSUE TITLE
Vue files and scope-slot

### ISSUE THREAD

**Issue by cdmoro** [vuejs/vuepress#469]
Hi, there's a strange behavior when I try to use components (mine and 3rd) with slots and slot-scope, vuepress can't see the slot-scoped variable. Thanks!

**Comment by ulivz** [comment]
Hi, thanks for your interest but please follow issue reporting guidelines, Github issues are for bug reports and feature requests only. You can ask questions on the [forum](https://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), or [StackOverflow](https://stackoverflow.com/tags/vue.js). If it turns out to be a bug, come back and open an issue with a proper reproduction repo 🙂

**Comment by cdmoro** [comment]
Ok, I'll google it. I think it's a bug, but if you say so... thanks you for the feedback.
