### ISSUE TITLE
Have content available in this.$page

### ISSUE THREAD

**Issue by Adam-Collier** [vuejs/vuepress#494]
#### What problem does this feature solve?

In a project I'm working on I have some consecutive elements which I want to wrap inside a div and style and atm there is no access to the rendered markdown content in the metadata. So by having access to the content you could potentially loop through each element,  add classes and wrap multiple elements in a div. This would keep your markdown clean (by not having to introduce html tags) and hopefully take a bit of hassle away.

#### What does the proposed API look like?

I was thinking something like $page.content, so it is page specific

#### How should this be implemented in your opinion?

add the rendered markdown elements to the $page object

#### Are you willing to work on this yourself?**

I am very new to vue (this is my first time using it!) But I will help however I can :)

**Comment by ulivz** [comment]
Thanks for your reporting. but we don't plan to add the markdown compiled content to `$page` since we should load all page's content on demand.

But there is a workaround for such case: you can use [Content Excerpt](https://vuepress.vuejs.org/guide/custom-themes.html#content-excerpt) and put the `<!-- more -->` comment at the bottom of your markdown file content. then you can access the markdown content via `$page.excerpt`.

**Comment by jorisnoo** [comment]
Using `<Content :pageKey="page.key"></Content>` to render the content of a page seems to work as well (in [Version 1.x](https://v1.vuepress.vuejs.org/guide/using-vue.html#built-in-components)).

**Comment by limitlessloop** [comment]
Hi, @ulivz do you know where I can view documentation about Content Excerpt, the link appears to be broken now and I would like to learn more about how I could add this functionality to my site. Many thanks.
