### ISSUE TITLE
Theme error building a site and sometimes even showing VuePress site

### ISSUE THREAD

**Issue by GustavoMarcante** [vuejs/vuepress#575]
#### Version
0.10.1

#### Steps to reproduce
I followed the instructions at https://vuepress.vuejs.org/guide/getting-started.html#global-installation:
```
yarn global add vuepress
echo '# Hello VuePress' > README.md
vuepress build
```
I also installed using npm and the same error happened.

#### What is expected?
A VuePress page with theme.

#### What is actually happening?
The (tiny) content was shown in a buggy theme,
with three black rectangles first and then the content without formatting,
as show at:
[VuePress.pdf](https://github.com/vuejs/vuepress/files/2095917/VuePress.pdf)

#### Other relevant information
In a certain moment, even the VuePress site loaded with the same error in my Ubuntu Desktop
(it did not happened in my Android cell phone).
I tried in two Ubuntu desktops, with 16.04 and 18.04.
If it is not a bug, but a installation error, at least the instructions could be cleaner, avoiding this error.

- OS: Ubuntu Linux 18.04 and 16.04 (two different desktops)
- Node.js version: 8.11.2
- Browser version: Both Firefox Quantum 60.0.2 and Google Chrome 67.0.3396.79 64 bits
- It is a global install
- Package manager for the install: Both npm and yarn

**Comment by GustavoMarcante** [comment]
The same display error, showing VuePress site https://vuepress.vuejs.org, was reported in https://github.com/vuejs/vuepress/issues/583, using Mac.
So I will edit the title.

**Comment by GustavoMarcante** [comment]
The three black rectangles comes from the <svg> tag in "sidebar-button" div.

**Comment by bobaekang** [comment]
I am having the precisely same issue here on a Windows machine, where `vuepress dev` gives me the expected page with correct formatting while the rendered static page from `vuepress build` does not. I tried both VuePress v0.12.0 and v0.13.1 (global install) and got the same result.

* OS: Windows 10
* Node: v8.9.3
* Chrome: v68.0.3440.84 (Official Build) (64-bit)
* Package manager: NPM

I also get the following warning message each time I try building: ` DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead`. I wonder if this is relevant.

I tried to delete all the service workers from other sites as suggested in #583 but the problem remains unresolved.

**Comment by GustavoMarcante** [comment]
Great, @bobaekang, it worked for me!
Thanks for sharing this solution!
My suggestion is to include this (or another related solution) in the instructions, as, in my point of view, it is not obvious, especially for those unfamiliar with Vue (one of the targets of VuePress).

**Comment by ulivz** [comment]
> "Why can't open the files that VuePress build directly? "

 This's question that's not very easy to explain. and this is not an issue from VuePress, but from [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin).

First, VuePress is based on [webpack](https://webpack.js.org/), In VuePress, the default [publicPath](https://webpack.js.org/guides/public-path/)(i.e [base](https://vuepress.vuejs.org/config/#base) in VuePress) is `/`, which causes all the assets to bring the starting slash. e.g.

``` html
<script type="text/javascript" src="/assets/js/app.9687e57b.js"></script>
```

instead of:

``` html
<script type="text/javascript" src="assets/js/app.9687e57b.js"></script>
```

So you cannot open it in local directly. To preview it in local, you need a a static server. `http-server` or `anywhere`, or others.

## publicPath 

> It allows you to specify the base path for all the assets within your application.

So if you deploy your site to a subdomain, it's a very useful feature - your source code will only need to maintain the relative path.

## References

- [VuePress > Base URL](https://vuepress.vuejs.org/guide/assets.html#base-url)
- https://github.com/jantimon/html-webpack-plugin/issues/635
- https://github.com/jantimon/html-webpack-plugin/issues/930

**Comment by daisybaicai** [comment]
Maybe you write the base and you don't need it.
I have the same problem when I push it to the github and build.
When I delete the base 'xx' in config.js, I have Solve this problem and get the correct style.
