### ISSUE TITLE
Documentation - CSS example

### ISSUE THREAD

**Issue by alexbainbridge** [vuejs/vuepress#687]
## Feature request

Took me a long time to find out that possible to change CSS by adding a CSS entry to .vuepress/override.styl

Documentation is not clear. I suggest an addition to the documentation

#### What problem does this feature solve?

People like me not spending "hours" trying to work out how to fix this

#### What does the proposed API look like?

Show something like

```
.hero img {
  width: 150px !important;
}
```

in the https://vuepress.vuejs.org/default-theme-config/#simple-css-override
 explanation

#### How should this be implemented in your opinion?

Add an example to the docs

#### Are you willing to work on this yourself?**

Think you should do the docs (!)

**Comment by ulivz** [comment]
So, where do you think it's not very clear? I think you can open a PR dorectly.

BTW, you don't need !important instead. 

ref: https://vuepress.vuejs.org/default-theme-config/#migrate-your-styles-to-style-styl

**Comment by ulivz** [comment]
We're closing this issue as stale as it's more than 20 days without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.

**Comment by diazgilberto** [comment]
I can't get `.vuepress/style.styl` to change anything in the page. I just have the following...

```
body {
  background-color: red;
}
```

and that is not affecting any page. I'm wondering if the `styl` file is getting compiled into `CSS` on save. I looked into the docs to see if another step is required or command to compile `styl` into `CSS` but couldn't find anything. I do have `.vuepress/override.styl` blank since I'm not wanting to change variables but instead adding custom styles.

**Comment by tiptronic** [comment]
same here

**Comment by RikkaW** [comment]
@diazgilberto @tiptronic `.vuepress/style.styl` is gone on v1.(https://v1.vuepress.vuejs.org/theme/inheritance.html#motivation)

**Comment by diazgilberto** [comment]
> @diazgilberto @tiptronic `.vuepress/style.styl` is gone on v1.(https://v1.vuepress.vuejs.org/theme/inheritance.html#motivation)

👍
