### ISSUE TITLE
When editing the markdown title, the page will be reloaded.

### ISSUE THREAD

**Issue by LinFeng1997** [vuejs/vuepress#765]
#### Version
0.14.2
#### Steps to reproduce
// readme.md
```
## test
```
modify to:
```
## test2
```
the page will be reloaded. 

#### What is expected?
the page content changed，but not be reloaded.

#### What is actually happening?
the page content change and reload.

#### Other relevant information

I recommend adding `reload:false` to the hot configuration of webpack-server.

- Your OS: Mac OS
- Node.js version: v8.9.2
- Browser version: Chrome 68
- Is this a global or local install? global
- Which package manager did you use for the install? npm

**Comment by ulivz** [comment]
This reloading is due to VuePress handled a manual update for `headers` and `frontmatter`, because they are not going to be part of the returned component.

With this manual update, all the `metadata` will be re-generated, so the page will be reloaded.

In addition, we don't plan to add `reload: false`, if you want to disable it, you can just open a Proxy.
