### ISSUE TITLE
Old docs 

### ISSUE THREAD

**Issue by ekoeryanto** [vuejs/vuepress#871]
## Bug report

Provide link to old docs and warn user that the v1.0 version is used to current docs

#### Other relevant information

- Your OS: 
- Node.js version: 
- Browser version: 
- Is this a global or local install? 
- Which package manager did you use for the install?

**Comment by ulivz** [comment]
See README.

**Comment by ekoeryanto** [comment]
I meant on the web

**Comment by mesqueeb** [comment]
I also cannot find a link to the old docs anywhere!
Does anyone know how to access the 0.x docs?

**Comment by ulivz** [comment]
Cannot find it anywhere???

![image](https://user-images.githubusercontent.com/23133919/52999480-e67d8000-3460-11e9-8f84-fac2fe0f6d0c.png)

![image](https://user-images.githubusercontent.com/23133919/52999643-44aa6300-3461-11e9-99f7-0945bb29004a.png)

**Comment by mesqueeb** [comment]
Thanks I found it!
The first image seems to be from the Github Repo and I was searching on the website. XD

Then what happened in my case is that I had clicked away that pop-up unconsciously out of habit of pop-ups. And I was literally searching that website for 10+ minutes and couldn't find a link anywhere. Only then to realise you need to do a page refresh in order to get that pop-up again! : D haha, I'm so stupid.  :'-)
