### ISSUE TITLE
[Discussion] Is there a better way to use layouts with current `LayoutDistributor`

### ISSUE THREAD

**Issue by meteorlxy** [vuejs/vuepress#878]
**Version 1.0.0-alpha.1**

Sorry for not obeying the issue template, but I just want to discuss the `LayoutDistributor` that introduced in `v1.0.0-alpha`, which seems like to be one of the major breaking changes.

This component is not complicated. What it does is changing the "root" component according to the `layout` option in frontmatter:

https://github.com/vuejs/vuepress/blob/ace3aec3dbcfd43d269edb5701aabcc653cae1a2/packages/%40vuepress/core/lib/app/components/LayoutDistributor.vue#L1-L16

When switching between pages with different layouts, the "root" component will be replaced by another one, i.e. current layout will be replaced **totally** by another layout.

However, different layouts may extend from a same parent-layout, so they have some parts in common, which should not be replaced "totally".

In a common scenario, one may want to add `transition` when switching between layouts, but the "root" component is replaced so no `transition` could be added.

---

In addition, `LayoutDistributor` also changed the way how default theme handle custom layouts. Following code is buggy / has no effect when working together with `LayoutDistributor`.

https://github.com/vuejs/vuepress/blob/ace3aec3dbcfd43d269edb5701aabcc653cae1a2/packages/%40vuepress/theme-default/layouts/Layout.vue#L32-L37

---

In my opinion:

- For theme makers: current `LayoutDistributor` could help them to set layouts without extra code. But the "old way" is more flexible and extendable, which may be preferred by theme makers.
- For theme users / docs writers: no difference.

**Comment by SebastianNiemann** [comment]
Besides the already mentioned usage of `this.$page.frontmatter.layout` (which I fully agree on, as we also use something like `<component :is="$site.themeConfig.layout"/>` to handle different layouts -- as the current implementation of `layout:` enforces to much redundancy in common layout features), I would also like to point out the enforced layout specialisation of 404-Routes, which makes them behave quite differently from other pages.

https://github.com/vuejs/vuepress/blob/d8e6ecc22205aeed4c770d3f6ef5758cccbecd75/packages/%40vuepress/core/lib/app/components/LayoutDistributor.vue#L9-L12

Currently, VuePress seems to behave very odd in these cases, since the 404s content can already be specified using a 404.md file (however, its content is sadly not leveraged for actual 404 cases to my knowledge, but fully replaced by the layout `NotFound.vue` file):

https://github.com/vuejs/vuepress/blob/69117563f15bfc313b130f3958c30e2b54615295/packages/%40vuepress/core/lib/build.js#L73-L76

However, the current implementation also forces the user to use another (or duplicated) layout by requiring `NotFound` as layout in these cases.

Given the current option to specify a new layout on demand, It would seem to be more expected and flexible (in case no additional layout is wanted), to simply provide a `404.md` to describe its content and choose the layout via the frontmatter options, in case a different layout is wanted.

Users with multiple sites and a common layout could greatly benefit from this separation of content and layout (as we already do for all other kind of pages), as the 404s content can freely be chosen for each individual page (for example to display different, useful links for a lost customer), instead of building a workaround by shifting all the content (e.g. as objects or HTML strings) into the `config.js`, to retrieve it within the layout file.

For example (based on the default 404):

404.md
```
---
title: 404 - Nothing to see here
layout: NotFound
---
# 404

> {{ getMsg() }}

[Take me home.](/)

<script>
const msgs = [
  `There's nothing here.`,
  `How did we get here?`,
  `That's a Four-Oh-Four.`,
  `Looks like we've got some broken links.`
]
export default {
  methods: {
    getMsg () {
      return msgs[Math.floor(Math.random() * msgs.length)]
    }
  }
}
</script>
```

and

NotFound.vue
```
<template>
  <div class="theme-container">
    <Content></Content>
  </div>
</template>

<script>
export default {}
</script>
```

**Comment by SebastianNiemann** [comment]
A quick fix to achieve the latter (to normalise the 404 handling) could be to change

https://github.com/vuejs/vuepress/blob/8003425898bc0a42e4320c0c44ff5c839b8cbb9d/packages/%40vuepress/core/lib/prepare/ClientComputedMixin.js#L18-L21

into

```js
return pages.find(page => page.path.toLowerCase() === '/404.html');
```

Given that the `/404.html` is always generated by

https://github.com/vuejs/vuepress/blob/69117563f15bfc313b130f3958c30e2b54615295/packages/%40vuepress/core/lib/build.js#L73-L76

, it is safe to assume that the `/404.html` is always existing.

However, it would add the breaking change that -- compared to now -- the `404.html`s content is actually used to present a file not found error (instead of ignoring it).

**Comment by lorisleiva** [comment]
Agreed, replacing the entire Layout feels weird to me as I'm used to have at least one common component to work with.

As a workaround I just don't use `layout` and use another keyword in my frontmatter, for example:

```yaml
---
title: Home
use: HomeLayout
---
```

Then I have complete control over my layout distribution (even for pages that did not provide the option in the frontmatter).

```js
computed: {
    layout () {
        if (this.$page.regularPath.startsWith('/articles')) {
            return 'ArticleLayout'
        }
        return this.$page.frontmatter.use || 'PageLayout'
    }
}
```

**Comment by meteorlxy** [comment]
After 1.0.0-alpha.32, if the layout in frontmatter does not exist, it will fallback to `Layout.vue`.

So another workaround is to have only one `Layout.vue` in the layouts dir, so that all layouts will fallback to it. Then handle `frontmatter.layout` as the old way in 0.x

**Comment by meteorlxy** [comment]
@lorisleiva Similar but not the same, as you can use `layout: HomeLayout` but do not have to use another keyword in your frontmatter after 1.0.0-alpha.32.

**Comment by lorisleiva** [comment]
Oh great! Sorry I didn’t get that from your previous message.

**Comment by ulivz** [comment]
Supported from https://github.com/vuejs/vuepress/blob/master/CHANGELOG.md#100-alpha38-2019-02-16
