### ISSUE TITLE
.vuepress/style.styl not loaded

### ISSUE THREAD

**Issue by ekoeryanto** [vuejs/vuepress#883]
#### Version
1.0

#### Other relevant information

- Your OS: 
- Node.js version: 
- Browser version: 
- Is this a global or local install? 
- Which package manager did you use for the install?

**Comment by x8x** [comment]
In the meantime, adding palette to `config.js` works fine:
```js
module.exports = {
	palette: {
		$accentColor = #000
	}
}
```
Wondering if having multiple ways to do the same thing doesn't complicate too much the code and its maintainability, I would much prefer to have one opinionated way to do things, but understand other may prefer other ways and/or that is done on purpose so that any plugin/submodule, etc, can configure/bypass defaults. If there are breaking changes form 0.x to 1.x I would definitely not add support keeping pre 1.x stuff working and provide instead an upgrade guide.

Btw, @ulivz Thanks! You have done an amazing work on this 1.0alpha !!  
I've been able to migrate to 1.x, some issues with paths and smart paths.

**Comment by ekoeryanto** [comment]
@x8x no, the solution doesn't work for me, I understand about the palette and implement that instead of deprecated `override.styl`

**Comment by ulivz** [comment]
@x8x I think you're mixed `override.styl`(changed to `palette`) and `style.styl`. of course we'll write migration guide.

**Comment by ekoeryanto** [comment]
for quick fix this issue:

```js
// .vuepress/config.js
const path = require('path')
module.exports = {
  palette: path.resolve(__dirname, 'palette.styl'),
}
```

```stylus
// .vuepress/palette.styl
$accentColor = #008080

@import './style.styl'

```

**Comment by ulivz** [comment]
@ekoeryanto Do not write styles in `palette` !!!

**Comment by ekoeryanto** [comment]
Thanks, I'll rename it until it's fixed 😄

**Comment by ulivz** [comment]
Sorry but I cannot reproduce it.

**Comment by ulivz** [comment]
I confirmed again and it works, I think you should be careful before creating an issue, please treasure each other's time.

**Comment by ekoeryanto** [comment]
@ulivz, I did clean cache and temp dir but still config.styl not loaded

**Comment by x8x** [comment]
@ulivz Right! Confused `style.styl` with `palette.styl`, so in my case it was `palette.styl` that was not loaded and had to write it into `config.js`. Probably better wait a couple days before reporting issues, you probably already know what needs to be fixed and are just short on time ;-)

**Comment by rwam** [comment]
Same here with the palette. I've tried to use `palette.styl` instead of `override.styl` with no luck. I'm using a `config.yml` for the settings, but a palette setting doesn't work either.

So I rollback to 0.14.4 because of confusing docs on https://vuepress.vuejs.org/config/#styling - the only way that work for me is the use of an `override.styl`. Should be clarified in the docs too.

**Comment by ulivz** [comment]
@rwam If you are using 0.14.x, you should go to https://v0.vuepress.vuejs.org. and for the next version, since it is still in the beta stage, all API is not yet fully determined, as well as all documents.
