### ISSUE TITLE
Concurrent build with `-j` option

### ISSUE THREAD

**Issue by Leedehai** [vuejs/vuepress#981]
#### What problem does this feature solve?
Accelerate `npm run docs:build` for a fairly large documentation site. For example, I hope building the documentation site for VueCLI ([link](https://cli.vuejs.org)) takes no more than one second or two on my MacBook Pro.

#### What does the proposed API look like?
`npm run docs:build -j` or `npm run docs:build -j8`, where the `-j` option specifies the number of concurrent jobs (like [GNU Make](https://www.gnu.org/software/make/manual/html_node/Parallel.html#Parallel)).

#### How should this be implemented in your opinion?
I think it's best to be left to you experts.

#### Are you willing to work on this yourself?**
Sorry I'm not that familiar with node.js..

**Comment by ulivz** [comment]
> I hope building the documentation site for VueCLI (link) takes no more than one second or two on my MacBook Pro.

There are many points that affect the speed of building a document. One is the configuration of your machine, the second is the number of your documents, and the third is whether you use the cache. Every build takes only one second or two? Who can do it?

> concurrent jobs

VuePress can only support multiple processes during the `renderPage` phase. Since there is only one build context, opening a multi-process build requires a lot of data to be transferred, so this does not significantly improve the rendering speed.

In addition, the build speed is more likely to be resolved by [webpack](https://webpack.js.org).
